name: Space Test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Initialization environment
        run: |
          df -h
          docker rmi $(docker images -q) 2>/dev/null
          df -h
          sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          df -h
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          df -h
          sudo swapoff -a
          df -h
          sudo rm -f /swapfile /mnt/swapfile
          df -h
          sudo apt-get -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* moby* snap*
          sudo apt install tree -y
          df -h
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          df -h
          git clone -b master https://github.com/coolsnowwolf/lede
          df -h
          cd lede
          mkdir package/luci-app-openclash
          cd package/luci-app-openclash
          git init
          git remote add origin https://github.com/vernesong/OpenClash.git
          df -h
          git config core.sparsecheckout true
          echo "luci-app-openclash" >> .git/info/sparse-checkout
          git pull --depth 1 origin master
          git branch --set-upstream-to=origin/master master
          tree ~
          df -h
